#include "lmnt/opcodes.h"

#include "lmnt/interpreter.h"

const lmnt_op_info lmnt_opcode_info[LMNT_OP_END] = {
    { "RETURN",    LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x00
    { "NOOP",      LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x01
    { "ASSIGNSS",  LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   }, // 0x02
    { "ASSIGNVV",  LMNT_OPERAND_STACK4,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK4   }, // 0x03
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x04
    { "ASSIGNSV",  LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK4   }, // 0x05
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x06
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x07
    { "ASSIGNIBS", LMNT_OPERAND_IMM,      LMNT_OPERAND_IMM,      LMNT_OPERAND_STACK1   }, // 0x08
    { "ASSIGNIBV", LMNT_OPERAND_IMM,      LMNT_OPERAND_IMM,      LMNT_OPERAND_STACK4   }, // 0x09
/*
    { "DLOADIIS",  LMNT_OPERAND_IMM,      LMNT_OPERAND_IMM,      LMNT_OPERAND_STACK1   },
    { "DLOADIIV",  LMNT_OPERAND_IMM,      LMNT_OPERAND_IMM,      LMNT_OPERAND_STACK4   },
    { "DLOADIRS",  LMNT_OPERAND_IMM,      LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   },
    { "DLOADIRV",  LMNT_OPERAND_IMM,      LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK4   },
    { "DSECLEN",   LMNT_OPERAND_IMM,      LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   },
*/
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x0A
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x0B
    { "ADDSS",     LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x0C
//    { "ADDVV",     LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK4   },
    { "SUBSS",     LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x0D
//    { "SUBVV",     LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK4   },
    { "MULSS",     LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x0E
//    { "MULVV",     LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK4   },
    { "DIVSS",     LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x0F
//    { "DIVVV",     LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK4   },
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x10
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x11
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x12
    { "REMSS",     LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x13
//    { "REMVV",     LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK4   },
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x14
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x15
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x16
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x17
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x18
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x19
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x1A
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x1B
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x1C
    { "SINR",      LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   }, // 0x1D
    { "COSR",      LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   }, // 0x1E
    { "TANR",      LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   }, // 0x1F
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x20
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x21
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x22
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x23
    { "ASINR",     LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   }, // 0x24
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x25
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x26
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x27
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x28
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x29
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x2A
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x2B
    { "ACOSR",     LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   }, // 0x2C
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x2D
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x2E
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x2F
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x30
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x31
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x32
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x33
    { "ATANR",     LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   }, // 0x34
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x35
    { "ATAN2R",    LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x36
    { "SINCOSR",   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x37
    { "POWSS",     LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x38
//    { "POWVV",     LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK4   },
//    { "POWVS",     LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK4   },
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x39
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x3A
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x3B
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x3C
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x3D
    { "SQRTS",     LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   }, // 0x3E
//    { "SQRTV",     LMNT_OPERAND_STACK4,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK4   },
//    { "LN",        LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   },
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x3F
    { "LOG2",      LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   }, // 0x40
//    { "LOG10",     LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   },
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x41
    { "ABSS",      LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   }, // 0x42
//    { "ABSV",      LMNT_OPERAND_STACK4,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK4   },
    { "MINSS",     LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x43
//    { "MINVV",     LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK4   },
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x44
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x45
    { "MAXSS",     LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x46
//    { "MAXVV",     LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK4   },
//    { "MINVS",     LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK4   },
//    { "MAXVS",     LMNT_OPERAND_STACK4,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK4   },
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x47
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x48
    { "FLOORS",    LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   }, // 0x49
//    { "FLOORV",    LMNT_OPERAND_STACK4,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK4   },
    { "ROUNDS",    LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   }, // 0x4A
//    { "ROUNDV",    LMNT_OPERAND_STACK4,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK4   },
    { "CEILS",     LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   }, // 0x4B
//    { "CEILV",     LMNT_OPERAND_STACK4,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK4   },
//    { "TRUNCS",    LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   },
//    { "TRUNCV",    LMNT_OPERAND_STACK4,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK4   },
    { "INDEXRIS",  LMNT_OPERAND_STACKREF, LMNT_OPERAND_IMM,      LMNT_OPERAND_STACK1   }, // 0x4C
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x4D
    { "INDEXRIR",  LMNT_OPERAND_STACKREF, LMNT_OPERAND_IMM,      LMNT_OPERAND_STACKREF }, // 0x4E
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x4F
    { "BRANCH",    LMNT_OPERAND_UNUSED,   LMNT_OPERAND_CODEPTR,  LMNT_OPERAND_CODEPTR  }, // 0x50
    { "BRANCHZ",   LMNT_OPERAND_STACK1,   LMNT_OPERAND_CODEPTR,  LMNT_OPERAND_CODEPTR  }, // 0x51
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x52
    { "BRANCHNZ",  LMNT_OPERAND_STACK1,   LMNT_OPERAND_CODEPTR,  LMNT_OPERAND_CODEPTR  }, // 0x53
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x54
    { "BRANCHPOS", LMNT_OPERAND_STACK1,   LMNT_OPERAND_CODEPTR,  LMNT_OPERAND_CODEPTR  }, // 0x55
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x56
    { "BRANCHNEG", LMNT_OPERAND_STACK1,   LMNT_OPERAND_CODEPTR,  LMNT_OPERAND_CODEPTR  }, // 0x57
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x58
    { "BRANCHUN",  LMNT_OPERAND_STACK1,   LMNT_OPERAND_CODEPTR,  LMNT_OPERAND_CODEPTR  }, // 0x59
    { "<INVALID>", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x5A
    { "CMP",       LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED   }, // 0x5B
    { "CMPZ",      LMNT_OPERAND_STACK1,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_UNUSED   }, // 0x5C
    { "BRANCHCEQ", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_CODEPTR,  LMNT_OPERAND_CODEPTR  }, // 0x5D
    { "BRANCHCNE", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_CODEPTR,  LMNT_OPERAND_CODEPTR  }, // 0x5E
    { "BRANCHCLT", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_CODEPTR,  LMNT_OPERAND_CODEPTR  }, // 0x5F
    { "BRANCHCLE", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_CODEPTR,  LMNT_OPERAND_CODEPTR  }, // 0x60
    { "BRANCHCGT", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_CODEPTR,  LMNT_OPERAND_CODEPTR  }, // 0x61
    { "BRANCHCGE", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_CODEPTR,  LMNT_OPERAND_CODEPTR  }, // 0x62
    { "BRANCHCUN", LMNT_OPERAND_UNUSED,   LMNT_OPERAND_CODEPTR,  LMNT_OPERAND_CODEPTR  }, // 0x63
    { "ASSIGNCEQ", LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x64
    { "ASSIGNCNE", LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x65
    { "ASSIGNCLT", LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x66
    { "ASSIGNCLE", LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x67
    { "ASSIGNCGT", LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x68
    { "ASSIGNCGE", LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x69
    { "ASSIGNCUN", LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1,   LMNT_OPERAND_STACK1   }, // 0x6A
    { "SUMV",      LMNT_OPERAND_STACK4,   LMNT_OPERAND_UNUSED,   LMNT_OPERAND_STACK1   }, // 0x6B
//   { "EXTCALL",   LMNT_OPERAND_DEFPTR,   LMNT_OPERAND_DEFPTR,   LMNT_OPERAND_STACKN   },
};

const lmnt_op_info* lmnt_get_opcode_info(lmnt_opcode op)
{
    return LMNT_LIKELY(op < LMNT_OP_END) ? &(lmnt_opcode_info[op]) : NULL;
}
