cmake_minimum_required(VERSION 3.14)

CPMAddPackage(
    NAME ghc
    GITHUB_REPOSITORY gulrak/filesystem
    VERSION 1.3.2
    OPTIONS
        "GHC_FILESYSTEM_BUILD_TESTING OFF"
        "GHC_FILESYSTEM_BUILD_EXAMPLES OFF"
        "GHC_FILESYSTEM_WITH_INSTALL OFF"
)